### ISSUE TITLE
Division by zero for files

### ISSUE THREAD

**Issue by sandreas** [wapmorgan/MediaFile#11]
Hello,

first I would like to thank you for this awesome project. Unfortunately with some of my files I get a `Division by zero` error, that is not catchable... 

It happens with multiple `mp3` files, which i cannot provide publicly due to copyright but I think you should in any case fix the possible `division by zero`. If you really need the files, feel free to contact me again, I'll try to provide you a sample.

Heres a trace:

```
... Division by zero (Code: 2) ...wapmorgan/mp3info/src/Mp3Info.php, line 384
#0 ...wapmorgan/mp3info/src/Mp3Info.php(384): {closure}(2, 'Division by zer...', '...', 384, Array)
#1 ...wapmorgan/mp3info/src/Mp3Info.php(279): wapmorgan\Mp3Info\Mp3Info->readMpegFrame(Resource id #24)
#2 ...wapmorgan/mp3info/src/Mp3Info.php(224): wapmorgan\Mp3Info\Mp3Info->parseAudio(Object(SplFileInfo), 8449196, 1)
#3 ...wapmorgan/media-file/src/Adapters/Mp3Adapter.php(15): wapmorgan\Mp3Info\Mp3Info->__construct(Object(SplFileInfo))
#4 ...wapmorgan/media-file/src/MediaFile.php(66): wapmorgan\MediaFile\Adapters\Mp3Adapter->__construct(Object(SplFileInfo))
#5 ...wapmorgan/media-file/src/MediaFile.php(44): wapmorgan\MediaFile\MediaFile->__construct(Object(SplFileInfo), 'audio', 'mp3')
#6 ...: wapmorgan\MediaFile\MediaFile::open(Object(SplFileInfo))
#7 {main}
```

I think that the `$this->sampleRate` variable is not set correctly. Since it is not possible to catch this error under normal circumstances, I wrote a little script to, that's why it is a trace and not a fatal error output:

```php
$path = 'path/to/mp3/files';

$directory = new \RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS | FilesystemIterator::UNIX_PATHS | FilesystemIterator::CURRENT_AS_FILEINFO);
$files = new \RecursiveIteratorIterator($directory);

set_error_handler(function ($errorCode, $errorMessage, $file, $line) {
    if (!(error_reporting() & $errorCode)) {
        return false;
    }
    throw new Exception(sprintf('%s (Code: %s) in %s, line %s', $errorMessage,$errorCode, $file, $line));
});

foreach ($files as $file) {
    if ($file->getExtension() !== "mp3") {
        continue;
    }
    try {
        $mediaFile = MediaFile::open($file);
    } catch (Throwable $t) {
        echo $file . PHP_EOL;
        echo " ===> exception: " . $t->getMessage() . PHP_EOL;
        echo $t->getTraceAsString().PHP_EOL;
    }
}
restore_error_handler();
```

**Comment by wapmorgan** [comment]
Update dependecies and check again

**Comment by sandreas** [comment]
Ok, I'll report back if I checked.

**Comment by sandreas** [comment]
Thank you. Seems to be fixed, at least it did not happen again. I'll reopen, if something else fails.
